services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - ENV=dev
      - PORT=8100
      - SURREAL_HOST=ws://db:8001/rpc
      - SURREAL_USER=root
      - SURREAL_PASS=root
      - SURREAL_DB=example
      - SURREAL_NS=dev
#     - GIN_MODE=release
    command: "./server"
    depends_on:
      - db

  db:
    image: surrealdb/surrealdb
    command: "start -b 0.0.0.0:8001 --user root --pass root file:/app/db/example.db"
    volumes:
      - data:/app/db

volumes:
  data:
